#!/bin/sh
set -e

case "$1" in
    configure)
        # Create directories
        mkdir -p /var/lib/tls-snoop/.config
        mkdir -p /var/cache/tls-snoop
        mkdir -p /var/log/tls-snoop

        # Reload systemd
        systemctl daemon-reload || true
        ;;
esac

#DEBHELPER#

exit 0
